### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by troublesomesync** [aXenDeveloper/ips-app-fontawesome6#3]
Unicode \e392, \f09b and \f1b7 no work

Exemple:
`[data-forumid="39"] .fa-arrow-right::before {
  content: "\f1b7";
}`

**Comment by aXenDeveloper** [comment]
> /e392
It's from Pro version.

> \f09b and \f1b7
![image](https://user-images.githubusercontent.com/58148176/190911905-11a47258-e7df-4cdf-b2dc-bdde82b22233.png)
