### ISSUE TITLE
FA 6.5.1 is out

### ISSUE THREAD

**Issue by Rushaway** [aXenDeveloper/ips-app-fontawesome6#4]
https://github.com/FortAwesome/Font-Awesome/releases/tag/6.5.1

**Comment by aXenDeveloper** [comment]
Hi,

Yes, I know that.
Unfortunately I'm sick now and I'll update as soon as possible.

Sorry about that

**Comment by aXenDeveloper** [comment]
New version is here: https://github.com/aXenDeveloper/ips-app-fontawesome6/releases/tag/v6.5.1

**Comment by Rushaway** [comment]
Hello, 6.5.2 is out!

**Comment by Rushaway** [comment]
Just a quick message to inform you FA 6.6.0 was released on Jul 7th, 2024
